name: Monorepo Diff
description: Trigger pipelines on changes in watched folders
author: https://github.com/buildkite-plugins
requirements:
  - git
configuration:
  properties:
    diff:
      type: string
    log_level:
      type: string
    watch:
      type: array
      properties:
        path:
          type: [string, array]
          minimum: 1
        generator:
          type: string
  required:
    - watch

# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite-plugins/buildkite-plugin-linter/master/lib/plugin-yaml-schema.yml
