#!/bin/bash
set -euo pipefail

ROOT="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
PLUGIN_NAME=monorepo-diff
COMPILE_IMAGE=public.ecr.aws/docker/library/golang:1.22.4-alpine

compile() {
    if command -v ${PLUGIN_NAME}-buildkite-plugin-bin > /dev/null 2>&1; then
        return 0;
    fi
    echo "~~~ Compiling ${PLUGIN_NAME} plugin"
    local tempdir
    tempdir="$(mktemp -d "/tmp/${PLUGIN_NAME}.XXXXXX")"
    docker run --name="compile-$BUILDKITE_JOB_ID" \
        -e CGO_ENABLED=0 \
        -v "$ROOT:/usr/src/app:ro" \
        -w /usr/src/app \
        "$COMPILE_IMAGE" \
        go build -v -o /tmp/${PLUGIN_NAME}-buildkite-plugin-bin
    docker cp "compile-$BUILDKITE_JOB_ID:/tmp/${PLUGIN_NAME}-buildkite-plugin-bin" "$tempdir/"
    docker rm "compile-$BUILDKITE_JOB_ID"
    export PATH="$tempdir:$PATH"
}

compile

monorepo-diff-buildkite-plugin-bin "$@"